// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"basic-go/lmbook/api/proto/gen/account/v1"
	"basic-go/lmbook/api/proto/gen/payment/v1"
	"basic-go/lmbook/reward/repository"
	"basic-go/lmbook/reward/repository/cache"
	"basic-go/lmbook/reward/repository/dao"
	"basic-go/lmbook/reward/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWechatNativeSvc(client pmtv1.WechatPaymentServiceClient,
	acli accountv1.AccountServiceClient) service.RewardService {
	gormDB := InitTestDB()
	rewardDAO := dao.NewRewardGORMDAO(gormDB)
	cmdable := InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	loggerV1 := InitLogger()
	wechatNativeRewardService := service.NewWechatNativeRewardService(client, rewardRepository, loggerV1, acli)
	return wechatNativeRewardService
}

// wire.go:

var thirdPartySet = wire.NewSet(InitTestDB, InitLogger, InitRedis)
